---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    worker_processes auto;
    worker_rlimit_nofile 4000;

    events {
      worker_connections 4000;
      multi_accept on;
      use epoll;
    }
    http {
      server {
            listen 80;
            location / {
              proxy_pass http://127.0.0.1:5000;
              proxy_http_version 1.1;
            }
      }
    }
